#-  Travis CI configuration file

#-  .travis.yml ~~
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 13 Feb 2015

language: node_js

node_js:
  - '0.12'
  - '0.10'
  - '0.8'
  - '0.6'

script:
  - make check

sudo: false

#-  vim:set syntax=yaml:
