.\" Manual page for Quanah
.\"
.\" quanah.1 ~~
.\"                                                     ~~ (c) SRW, 12 Aug 2012
.\"                                                 ~~ last updated 12 Mar 2015
.\"
.TH QUANAH "1" "12 March 2015" "version 0.3.0" "USER COMMANDS"

.SH NAME
.B "quanah" - Event-driven concurrency for ECMAScript and JavaScript

.SH SYNOPSIS
\-

.SH DESCRIPTION
\-

.SH OPTIONS
\-

.SH EXIT STATUS
\-

.SH NOTES
\-

.SH BUGS
No known bugs exist at this time :\-)

.SH AUTHOR
Sean Wilkinson

.SH SEE ALSO
Project page:
.I https://qmachine.github.io/quanah/

.\" vim:set syntax=groff:
